version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gatolandia-api:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/gatolandia
      DATABASE_USERNAME: gatolandia
      DATABASE_PASSWORD: gatolandia
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: gatolandia
      POSTGRES_USER: gatolandia
      POSTGRES_PASSWORD: gatolandia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
