CREATE TABLE tb_donos
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome         VARCHAR(255),
    idade        INT,
    endereco     VARCHAR(255),
    email        VARCHAR(255),
    celular      VARCHAR(255),
    possui_gatos BOOLEAN,
    CONSTRAINT pk_tb_donos PRIMARY KEY (id)
);

CREATE TABLE tb_gatos
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome        VARCHAR(255),
    cor         VARCHAR(255),
    raca        VARCHAR(255),
    idade       INT                                     NOT NULL,
    castrado    BOOLEAN                                 NOT NULL,
    tb_donos_id BIGINT,
    CONSTRAINT pk_tb_gatos PRIMARY KEY (id)
);

ALTER TABLE tb_donos
    ADD CONSTRAINT uc_tb_donos_celular UNIQUE (celular);

ALTER TABLE tb_donos
    ADD CONSTRAINT uc_tb_donos_email UNIQUE (email);

ALTER TABLE tb_gatos
    ADD CONSTRAINT FK_TB_GATOS_ON_TB_DONOS FOREIGN KEY (tb_donos_id) REFERENCES tb_donos (id);
